name: CI Pipeline

on:
  push:
    branches: [ "main" , "frontend"]
  pull_request:
    branches: [ "main" , "frontend"]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # ---------------------------
      # Backend (FastAPI - Python)
      # ---------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Lint backend code (flake8)
        run: |
          pip install flake8
          flake8 backend

      # ---------------------------
      # Frontend (React + Vite)
      # ---------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Lint frontend code (eslint)
        run: |
          cd frontend
          npx eslint .

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # ---------------------------
      # Placeholder for tests
      # ---------------------------
      - name: Run backend tests
        run: |
          echo "Add pytest here if you write backend tests"
          # Example: pytest --maxfail=1 --disable-warnings -q

      - name: Run frontend tests
        run: |
          echo "Add React tests here"
          # Example: cd frontend && npm test -- --watchAll=false
